import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import {loadPayrollFacts} from '../src/computo-cloud-v2.js';
import {aggregateFacts} from '../src/economics-v2.js';
const repo=process.env.COMPUTO_REPO||resolve('../computo-aac');
test('real producer → computo_sync payload → a different device consumer', {skip:!existsSync(resolve(repo,'app/page.tsx'))&&'Set COMPUTO_REPO to run the cross-repository contract'},async()=>{
 const require=createRequire(pathToFileURL(resolve(repo,'package.json'))),ts=require('typescript');
 const {calendarContext}=await import(pathToFileURL(resolve(repo,'tests/helpers/calendar-context.mjs')));
 const context=await calendarContext();
 const source=readFileSync(resolve(repo,'app/page.tsx'),'utf8');
 const parsed=ts.createSourceFile('page.tsx',source.slice(0,source.indexOf('export default function Home')),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const body=parsed.statements.filter(n=>!ts.isImportDeclaration(n)).map(n=>n.getText(parsed)).join('\n');
 vm.runInContext(ts.transpileModule(body,{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText+'\nglobalThis.api={payrollFactsFor,DEFAULT_PROFILE};',context);
 const {payrollFactsFor,DEFAULT_PROFILE}=context.api;
 const payload=JSON.parse(JSON.stringify(payrollFactsFor({1:{days:[{day:2,status:'AGCG',special:'MODIFICACION',modificationPlacement:'PERSONALIZADO',customStart:'12:00',customEnd:'21:00',extraHours:0}]}},2026,{...DEFAULT_PROFILE,contract:'75'})));
 const key='metro-payroll-facts-v1-2026',cloud=new Map(),local=new Map([[key,JSON.stringify(payload)]]);
 const session={access_token:'test-only',expires_at:9999999999};
 const sync=vm.createContext({exports:{},localStorage:{getItem:k=>local.get(k)??null,setItem:(k,v)=>local.set(k,v)},navigator:{onLine:true},readSharedSession:()=>session,authenticatedUserId:async()=> 'test-user',SUPABASE_URL:'https://test.invalid',SUPABASE_PUBLIC_KEY:'test-only',fetch:async(url,options)=>{const row=JSON.parse(options.body);cloud.set(row.storage_key,row.payload);return {ok:true};}});
 const syncSource=readFileSync(resolve(repo,'app/computo-sync.ts'),'utf8').replace(/^import .*?;\s*/,'');
 vm.runInContext(ts.transpileModule(syncSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,sync);
 assert.equal(await sync.exports.pushStorageKey(key),true);
 let calls=0;
 const remote=await loadPayrollFacts('2026-01',{getItem:k=>k==='sb-hhenkvendzengggrgook-auth-token'?JSON.stringify(session):null},async()=>({ok:true,json:async()=>++calls===1?{id:'test-user'}:calls===2?[{estado:'aprobado'}]:[{payload:cloud.get(key)}]}));
 assert.equal(remote.profile.percent,75);
 assert.equal(aggregateFacts(remote.facts,'ordinaryHours').value,9);
 assert.equal(aggregateFacts(remote.facts,'horaNonaHours').value,1);
 assert.equal(aggregateFacts(remote.facts,'ordinaryHours').missing,30);
 assert.equal(aggregateFacts(remote.facts,'workedHolidayDays').value,null);
});
