import {categories,visibleConcepts,datedRates} from './presentation.js';
import {concepts,money,tariff} from './catalogue.js';
import {calculate} from './engine.js';
import {readComputo,mergeDays,parseSnapshot,sanitizeDay,sanitizeProfile,statuses,demo} from './data.js';
const root=document.querySelector('main');
const key='nomina-local-v1';
let period=new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0');
let section='home',search='',group='',detail=null,extra={schema:'nomina-facts-v1',profile:null,days:[]},settings={},source='',notice='',useDemo=false;
try { const saved=JSON.parse(localStorage.getItem(key)||'null'); if(saved){extra=parseSnapshot(saved.facts);source='Còpia local guardada';} }catch{notice='La còpia guardada no és compatible. No s’ha utilitzat.';}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>new Intl.NumberFormat('ca-ES',{maximumFractionDigits:4}).format(n);
const time=n=>Number.isFinite(n)?`${Math.floor(n/60)} h ${Math.round(n%60).toString().padStart(2,'0')} min`:'—';
const norm=s=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();
function context(){const base=useDemo?{days:[],profile:null}:readComputo(localStorage,+period.slice(0,4));const input=settings[period]||{};const profile=input.profile||extra.profile||base.profile;const days=mergeDays(base.days,extra.days);return {base,input,profile,days,results:calculate(period,days,profile,input)};}
function summary(c,r){return `<span class="badge">${esc(r.state)}</span><div class="result">${r.amount!==null?money(r.amount):r.units!==null?`${num(r.units)} <small>${esc(c.unit)}</small>`:'—'}</div><p class="meta">${r.resolved} jornades/components amb unitats · ${r.pending} pendents${r.missing?` · ${r.missing} dates sense dades`:''}</p>${r.candidates?`<p>${r.candidates} candidats identificats; encara no abonables.</p>`:''}${r.amount!==null?'<p class="meta">Subtotal estimat, no inclou les parts pendents. Arrodoniment de presentació a cèntims, no certificació del criteri de nòmina.</p>':''}`;}
function rows(r){return r.rows.length?`<details class="daily"><summary>Veure ${r.rows.length} jornades · origen i càlcul</summary><div class="table-wrap"><table><thead><tr><th>Data / situació</th><th>Interval</th><th>22–06</th><th>Unitats retribuïbles</th><th>Explicació</th></tr></thead><tbody>${r.rows.map(d=>`<tr><td>${esc(d.date)}<small>${esc(d.status)}</small></td><td>${esc(d.start||'—')} → ${esc(d.end||'—')}</td><td>${time(d.overlap)}</td><td>${d.units===null?'Pendent':num(d.units)}${d.candidateUnits!=null?`<small>Tram conegut: ${num(d.candidateUnits)} h</small>`:''}</td><td>${esc(d.reason)}</td></tr>`).join('')}</tbody></table></div></details>`:'<p class="meta">Sense detall diari disponible per a aquest concepte.</p>';}
function card(c,r){return `<article class="card"><div class="card-top"><span class="eyebrow">${esc(c.group)}</span><span class="source-id">${esc(c.source.split(';')[0])}</span></div><h2>${esc(c.name)}</h2>${section==='pay'?summary(c,r):''}<p class="description">${esc(c.what)}</p><button class="link" data-detail="${c.id}">Norma i detall del càlcul →</button></article>`;}
function periodControl(){return `<label class="period">Període d’activitat<input id="period" type="month" min="2000-01" max="2100-12" value="${period}"></label>`;}
function fiche(c,r,ctx){
 const rates=datedRates(c);
 const personal=section==='pay';
 return `<button class="link" id="back">← Tornar</button><article class="fiche"><span class="eyebrow">${esc(c.group)}</span><h1>${esc(c.name)}</h1>
 ${personal?`<div class="personal">${summary(c,r)}${r.notes.map(n=>`<p class="meta">${esc(n)}</p>`).join('')}${rows(r)}</div>`:''}
 <div class="rules">${[['Què és',c.what],['Quan es genera',c.when],['Regla',c.rule],['Fórmula',c.formula],['Particularitats',c.particular],['Activitat i pagament',c.payment],['Certesa i vigència',c.certainty]].map(([title,text])=>`<section><h2>${esc(title)}</h2><p>${esc(text)}</p></section>`).join('')}
 <section><h2>Tarifes documentades</h2>${rates.length?`<ul class="rates">${rates.map(t=>`<li><strong>${t.year} · ${money(t.value)} / ${esc(c.unit)}</strong><p>${esc(t.source)}</p></li>`).join('')}</ul><p class="meta">Cada tarifa conserva el seu any i àmbit. No s’extrapola a altres períodes.</p>`:`<p>${esc(c.rateNote||'No consta una tarifa acreditada en aquesta selecció documental.')}</p>`}</section>
 <section><h2>Font</h2><p>${esc(c.source)}</p><a class="link" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Consultar font (pot requerir accés intern) ↗</a></section></div>
 ${personal?`<form id="rate-form" class="editor"><h2>Completar una tarifa del període</h2><p>No canvia la norma ni resol condicions pendents. Es tracta com a dada aportada per tu, no com a tarifa oficial. Només per a ${esc(period)}.</p><div class="fields"><label>Tarifa €/unitat<input name="rate" type="number" min="0" step="any" required value="${esc(ctx.input[c.id]?.rate??'')}"></label><label>Font i vigència de la tarifa<input name="source" maxlength="180" required value="${esc(ctx.input[c.id]?.source??'')}" placeholder="Taula o rebut i període"></label></div>${c.id==='vacances'?`<label class="check"><input name="vacation" type="checkbox" ${ctx.input.vacationConfirmed?'checked':''}>Confirmo que aquests dies són liquidables i que la mitjana és individual.</label>`:''}<button type="submit">Aplicar al període</button><button type="button" id="clear-rate" class="secondary">Treure tarifa aportada</button></form>`:`<button data-personal="${c.id}" class="secondary">Relacionar amb les meves dades →</button>`}</article>`;
}
function dataPanel(ctx){return `<details class="data-panel"><summary>Dades locals · completar o revisar</summary><p>Cómputo aporta situacions finals i perfil. No desa els horaris resolts ni la nocturnitat diària: aquests camps requereixen una instantània compatible o una entrada declarada. No es reprodueixen els torns ni es consulta cap servidor.</p><div class="actions"><label class="button secondary">Importar instantània JSON<input id="import" type="file" accept="application/json,.json" hidden></label><button id="demo" class="secondary">Provar exemple fictici</button><button id="save" class="secondary">Guardar còpia local</button><button id="remove" class="secondary">Eliminar còpia de Nòmina</button><button id="refresh" class="secondary">Rellegir Cómputo</button></div><p class="meta">La importació és el format propi nomina-facts-v1, no un exportador ja existent de Cómputo. Les tarifes i confirmacions són només d’aquesta sessió. No es llegeixen noms, matrícula, notes, fotos ni credencials. Eliminar la còpia no altera Cómputo.</p><form id="profile-form"><h3>Perfil efectiu de ${esc(period)}</h3><div class="fields"><label>Torn<select name="turn"><option value="">Sense confirmar</option>${['T1','T2','T4','T5','T8'].map(t=>`<option ${ctx.profile?.turn===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Percentatge (T8)<input name="percent" type="number" min="0.01" max="100" step="any" value="${esc(ctx.profile?.percent??'')}"></label></div><label class="check"><input type="checkbox" name="confirmed" ${ctx.input.monthConfirmed?'checked':''}>Confirmo categoria AAC, perfil vigent i mes íntegre elegible, sense altes ni ajustos/absències que afectin els complements mensuals.</label><button>Aplicar perfil al període</button></form><form id="day-form"><h3>Completar una jornada</h3><p>Substitueix només la còpia de Nòmina d’aquesta data. No modifica Cómputo. Les excepcions identificades no es resolen amb una casella.</p><div class="fields"><label>Data<input name="date" type="date" required value="${period}-01"></label><label>Situació final<select name="status">${statuses.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Entrada<input name="start" type="time"></label><label>Sortida<input name="end" type="time"></label></div><label class="check"><input type="checkbox" name="ordinary">Confirmo interval ordinari efectiu, sense pauses, canvi d’hora, Nadal ni Non Stop extraordinari pendents; nocturnitat variable, no fixa.</label><label class="check"><input type="checkbox" name="nona">Confirmo adscripció a còmput i que el dia/servei és elegible per I-53 (divendres, dissabte, diumenge o festiu).</label><button>Aplicar jornada declarada</button></form><p class="meta">En localhost no es pot llegir l’emmagatzematge de github.io. En el mateix origen i navegador es rellegeixen les dades automàticament. Els perfils històrics s’han de confirmar per període.</p></details>`;}
function searchBox(){return `<label class="search-label">Cerca un concepte<input id="search" type="search" value="${esc(search)}" placeholder="Per exemple: nocturnitat, Hora Nona, conveni…"></label>`;}
function connection(ctx){const count=ctx.days.filter(d=>d.date.startsWith(period+'-')).length;return `<button class="connection" data-section="pay"><span class="connection-icon" aria-hidden="true">▦</span><span><strong>${useDemo?'Exemple fictici actiu':count?'Dades locals de Còmput AAC disponibles':'Còmput AAC · opcional'}</strong><small>${count?'Consulta el període, la procedència i les dades pendents.':'Pots consultar totes les normes sense utilitzar Còmput. Si tens dades locals compatibles, les aprofitarem.'}</small></span><span aria-hidden="true">›</span></button>`;}
function render(){const ctx=context();const count=ctx.days.filter(d=>d.date.startsWith(period+'-')).length;
 const list=visibleConcepts(concepts,search,group);
 const home=section==='home'&&!detail;
 root.innerHTML=`${home?`<section class="hero"><img src="./assets/nomina-512.png" width="128" height="128" alt=""><div><h1>Nòmina</h1><p>Entén els conceptes<br>de la teva nòmina</p></div></section>${searchBox()}`:`<div class="intro"><div><button class="link" data-section="home">← Inici de Nòmina</button>${detail?'':`<h1>${section==='pay'?'La meva nòmina':'Conceptes'}</h1>`}</div>${section==='pay'?periodControl():''}</div>`}
 ${!home?`<nav aria-label="Seccions"><button data-section="pay" aria-pressed="${section==='pay'}">La meva nòmina</button><button data-section="concepts" aria-pressed="${section==='concepts'}">Conceptes</button></nav>`:''}
 ${notice?`<p class="notice" role="status">${esc(notice)}</p>`:''}
 ${section==='pay'?`<div class="context"><span class="dot"></span><div><strong>${useDemo?'EXEMPLE FICTICI · no són dades teves':source||(count?'Dades locals de Cómputo':'Sense dades personals')}</strong><p>${count} dates disponibles en ${period}. ${ctx.profile?.turn?`${ctx.profile.turn} · ${ctx.profile.percent??'?'} % · perfil ${ctx.input.monthConfirmed?'confirmat per tu':'pendent de confirmar per al període'}.`:''} El mes de pagament pot ser diferent.</p>${ctx.base.warning?`<p>${esc(ctx.base.warning)}</p>`:''}</div></div>`:''}
 ${detail?fiche(concepts.find(c=>c.id===detail),ctx.results.find(r=>r.id===detail),ctx):home&&!search?`<div class="entry-grid"><button data-section="pay" class="entry primary"><span class="entry-icon" aria-hidden="true">▥</span><span><strong>La meva nòmina</strong><small>Entén els conceptes del teu període amb les dades disponibles</small></span><b aria-hidden="true">›</b></button><button data-section="concepts" class="entry"><span class="entry-icon" aria-hidden="true">▤</span><span><strong>Conceptes</strong><small>Normes, fórmules, tarifes i fonts. No cal tenir dades de Còmput.</small></span><b aria-hidden="true">›</b></button></div><div class="category-heading"><h2>Categories de conceptes</h2><button class="link" data-section="concepts">Veure tots →</button></div><div class="categories">${categories.map(g=>`<button class="category" data-group="${g.id}"><span aria-hidden="true">${g.icon}</span><strong>${g.name}</strong><small>${g.text}</small></button>`).join('')}</div><p class="meta">8 fitxes disponibles en aquesta primera versió.</p>${connection(ctx)}`:`${section==='concepts'?`${searchBox()}<div class="category-filters"><button data-group="" aria-pressed="${!group}">Tots</button>${categories.map(g=>`<button data-group="${g.id}" aria-pressed="${group===g.id}">${g.name}</button>`).join('')}</div>`:''}${section==='pay'?'<p class="caption">Subtotals independents. Cap dada desconeguda es converteix en zero. No se sumen com una nòmina neta.</p>':''}<div class="grid" id="cards">${(section==='pay'?concepts:list).map(c=>card(c,ctx.results.find(r=>r.id===c.id))).join('')||'<p>No hi ha coincidències entre les 8 fitxes disponibles. El diccionari s’ampliarà més endavant.</p>'}</div>`}
 ${section==='pay'?dataPanel(ctx):''}`;
 bind();}
function updateInput(v){settings[period]={...(settings[period]||{}),...v};}
function bind(){document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{group=b.dataset.group;section='concepts';detail=null;render();});document.querySelectorAll('[data-personal]').forEach(b=>b.onclick=()=>{section='pay';detail=b.dataset.personal;render();window.scrollTo(0,0);});document.querySelector('#period')?.addEventListener('change',e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){period=e.target.value;render();}});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;detail=null;search='';group='';notice='';render();window.scrollTo(0,0);});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{detail=b.dataset.detail;render();window.scrollTo(0,0);});document.querySelector('#back')?.addEventListener('click',()=>{detail=null;render();});document.querySelector('#search')?.addEventListener('input',e=>{const pos=e.target.selectionStart;search=e.target.value;render();const el=document.querySelector('#search');el.focus();el.setSelectionRange(pos,pos);});document.querySelector('#group')?.addEventListener('change',e=>{group=e.target.value;render();});
if(document.querySelector('#import')) document.querySelector('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Fitxer massa gran (màxim 2 MB).');const x=parseSnapshot(await file.text());extra=x;useDemo=false;source='Instantània importada · dades declarades';notice='Importació local completada. No s’ha enviat cap dada.';settings={};}catch(error){notice=error.message;}render();};
if(document.querySelector('#demo')) document.querySelector('#demo').onclick=()=>{extra=demo(period);useDemo=true;source='Exemple fictici';settings={};notice='Exemple sintètic: 20 jornades ordinàries resoltes, una sense horari i la resta descans. Pots afegir una tarifa per comprovar el subtotal.';render();};
if(document.querySelector('#save')) document.querySelector('#save').onclick=()=>{try{if(useDemo){notice='L’exemple fictici no es desa com a perfil personal.';}else{localStorage.setItem(key,JSON.stringify({facts:parseSnapshot({schema:'nomina-facts-v1',profile:context().profile,days:context().days})}));notice='Còpia guardada només en aquest navegador. Les confirmacions i tarifes no es guarden.';}}catch{notice='No s’ha pogut guardar la còpia.';}render();};
if(document.querySelector('#remove')) document.querySelector('#remove').onclick=()=>{localStorage.removeItem(key);extra={schema:'nomina-facts-v1',profile:null,days:[]};settings={};source='';useDemo=false;notice='Còpia de Nòmina eliminada. Cómputo continua intacte i es torna a llegir.';render();};
if(document.querySelector('#refresh')) document.querySelector('#refresh').onclick=()=>{notice='Dades rellegides. Les jornades declarades/importades a Nòmina prevalen sobre la còpia de Cómputo; elimina la còpia per tornar a l’origen.';render();};
if(document.querySelector('#profile-form')) document.querySelector('#profile-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);updateInput({profile:sanitizeProfile({turn:f.get('turn'),percent:f.get('percent')}),monthConfirmed:f.has('confirmed')});notice='Perfil aplicat només a aquest període.';render();};
if(document.querySelector('#day-form')) document.querySelector('#day-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const old=context().days.find(d=>d.date===f.get('date'));try{const d=sanitizeDay({...old,date:f.get('date'),status:f.get('status'),start:f.get('start'),end:f.get('end'),ordinaryConfirmed:f.has('ordinary'),nonaEligible:f.has('nona'),resolvedVersion:null,nightPayableMinutes:null,nightOverlapMinutes:null,source:'manual'});extra.days=mergeDays(extra.days,[d]);notice='Jornada declarada aplicada a Nòmina. Cómputo no ha canviat.';}catch(error){notice=error.message;}render();};
document.querySelector('#rate-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);updateInput({[detail]:{rate:Number(f.get('rate')),source:f.get('source')},...(detail==='vacances'?{vacationConfirmed:f.has('vacation')}: {})});notice='Tarifa aportada per tu aplicada únicament al període seleccionat.';render();});document.querySelector('#clear-rate')?.addEventListener('click',()=>{updateInput({[detail]:null});render();});}
window.addEventListener('storage',e=>{if(e.key?.startsWith('metro-'))render();});
render();

if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
