export const COMPUTO_VERSION='e5bbd59b2cfbfe2b0f68f4b93f6bc2d8f2b371d0';
export const statuses=['AGCG','DCOM','FEST','VACACIONES','VACACIONES_PENDIENTES','VAC_ANTERIOR','MINI','LAUDO','RJ','FORMACION','REVISION_MEDICA','ENFERMEDAD','PERMISO','VISPERA_FESTIVO','HUELGA_LEGAL','COMPUTO_ANTERIOR','COMPUTO_ACTUAL','REVISAR'];
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
const cleanClock=v=>typeof v==='string'&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(v)?v:null;
const number=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:null;
export function sanitizeDay(d){if(!d||!validDate(d.date)||!statuses.includes(d.status))throw Error('Data o situació de jornada no vàlida. No s’ha importat el fitxer.');return {date:d.date,status:d.status,start:cleanClock(d.start),end:cleanClock(d.end),category:typeof d.category==='string'?d.category.slice(0,60):null,special:typeof d.special==='string'?d.special.slice(0,50):'NINGUNA',priorOrigin:['VACACIONES','RJ','COMPUTO'].includes(d.priorOrigin)?d.priorOrigin:null,ordinaryConfirmed:d.ordinaryConfirmed===true,nonaEligible:d.nonaEligible===true,nightOverlapMinutes:number(d.nightOverlapMinutes),nightPayableMinutes:number(d.nightPayableMinutes),nightReason:typeof d.nightReason==='string'?d.nightReason.slice(0,300):'',resolvedVersion:d.resolvedVersion===COMPUTO_VERSION?d.resolvedVersion:null,source:d.source==='manual'?'manual':'importat'};}
export function sanitizeProfile(p){return {turn:['T1','T2','T4','T5','T8'].includes(p?.turn)?p.turn:null,percent:p?.turn&&p.turn!=='T8'?100:(Number.isFinite(Number(p?.percent??p?.contract))&&Number(p?.percent??p?.contract)>0&&Number(p?.percent??p?.contract)<=100?Number(p.percent??p.contract):null)};}
export function parseSnapshot(raw){const x=typeof raw==='string'?JSON.parse(raw):raw;if(x?.schema!=='nomina-facts-v1'||!Array.isArray(x.days)||x.days.length>4000)throw Error('Format incompatible. Cal una instantània nomina-facts-v1; no s’accepta un fitxer arbitrari de Cómputo.');const days=x.days.map(sanitizeDay);if(new Set(days.map(d=>d.date)).size!==days.length)throw Error('Hi ha dates duplicades; revisa el fitxer.');return {schema:'nomina-facts-v1',profile:sanitizeProfile(x.profile),days};}
// Read-only adapter for the existing 1-based month keys. No repair, schedules,
// authentication, identity, notes, photographs or writes to Cómputo storage.
export function readComputo(storage,year){let profile=null,days=[],warning='';try{profile=sanitizeProfile(JSON.parse(storage.getItem('metro-profile-v2')||storage.getItem('metro-profile-v1')||'null'));const plan=JSON.parse(storage.getItem(`metro-year-${year}`)||'null');if(plan)for(const [month,p] of Object.entries(plan)){if(!Number.isInteger(+month)||+month<1||+month>12||!Array.isArray(p.days))throw Error();for(const d of p.days){const date=`${year}-${String(month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`;const custom=d.modificationPlacement==='PERSONALIZADO';days.push(sanitizeDay({date,status:d.status,start:custom?d.customStart:null,end:custom?d.customEnd:null,special:d.special,priorOrigin:d.priorOrigin}));}}if(new Set(days.map(d=>d.date)).size!==days.length)throw Error();}catch{days=[];warning='No s’han pogut llegir les dades de Cómputo. No s’han alterat ni reparat.';}return {profile,days,warning};}
export function mergeDays(base,extra){const m=new Map(base.map(d=>[d.date,d]));for(const d of extra)m.set(d.date,d);return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date));}
export function demo(period){const year=+period.slice(0,4),month=+period.slice(5);const count=new Date(year,month,0).getDate();return parseSnapshot({schema:'nomina-facts-v1',profile:{turn:'T8',percent:85.81},days:Array.from({length:count},(_,i)=>({date:`${period}-${String(i+1).padStart(2,'0')}`,status:i<21?'AGCG':'DCOM',start:i<20?'18:46':null,end:i<20?'02:50':null,ordinaryConfirmed:i<20,nonaEligible:false,source:'manual'}))});}
