import {concepts,tariff} from './catalogue.js';
import {COMPUTO_VERSION} from './data.js';
const work=new Set(['AGCG','VISPERA_FESTIVO','COMPUTO_ACTUAL','COMPUTO_ANTERIOR','FORMACION','REVISION_MEDICA']);
const rest=new Set(['DCOM','FEST','MINI','LAUDO','RJ','VACACIONES','VAC_ANTERIOR']);
const uncertain=new Set(['REVISAR','PERMISO','ENFERMEDAD','HUELGA_LEGAL','VACACIONES_PENDIENTES']);
export function interval(start,end){if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(start)||! /^(?:[01]\d|2[0-3]):[0-5]\d$/.test(end)||start===end)return null;const clock=s=>+s.slice(0,2)*60 + +s.slice(3);const a=clock(start);let b=clock(end);if(b<a)b+=1440;let night=0;for(let k=-1;k<=1;k++)night+=Math.max(0,Math.min(b,k*1440+1800)-Math.max(a,k*1440+1320));return {minutes:b-a,night,payable:night>240?b-a:night,a,b};}
export function nightResult(d,profile){if(rest.has(d.status))return {units:0,reason:'Sense activitat nocturna nova',excluded:true};if(uncertain.has(d.status)||!work.has(d.status))return {units:null,reason:'Situació personal pendent o absència amb tractament propi'};const t=interval(d.start,d.end);let reason=d.nightReason;
if(profile?.turn!=='T8')reason||='Àmbit de nocturnitat del perfil pendent';
if(d.category?.endsWith('_FINS_23H'))reason||='Jornada abonada i presència de Nadal pendents';
if(d.category?.includes('CANVI_HORA')&&(!t||t.night>0))reason||='Canvi d’hora pendent';
if(d.special==='NON_STOP_EXTRA')reason||='Non Stop extraordinari pendent';
if(['FORMACION','REVISION_MEDICA'].includes(d.status))reason||='Horari efectiu i abonament d’aquesta situació pendents';
if(reason)return {units:null,overlap:t?.night,reason};
if(d.resolvedVersion===COMPUTO_VERSION&&Number.isFinite(d.nightPayableMinutes)&&d.nightPayableMinutes>=0&&d.nightPayableMinutes<=1440&&Number.isFinite(d.nightOverlapMinutes)&&d.nightOverlapMinutes<=480)return {units:d.nightPayableMinutes/60,overlap:d.nightOverlapMinutes,reason:'Resultat diari de Cómputo I-83; sense aplicar de nou el percentatge'};
if(!t)return {units:null,reason:'Falta l’interval resolt: Cómputo no el desa al perfil'};
if(!d.ordinaryConfirmed)return {units:null,overlap:t.night,reason:'Confirma interval ordinari sense pauses ni excepcions pendents'};
return {units:t.payable/60,overlap:t.night,reason:t.night>240?'Més de 4 h: jornada completa':'Fins a 4 h incloses: només el tram nocturn'};}
function specialEvents(d){const t=interval(d.start,d.end);if(!t)return [];const year=+d.date.slice(0,4);const defs=[[2023,12,25],[2024,1,1],[2024,1,6],[2025,6,24],[2026,9,24]];const start=Date.parse(d.date+'T00:00:00Z')/60000+t.a,end=start+t.minutes;const hits=[];for(const y of [year,year+1])for(const [from,m,day] of defs){if(y<from)continue;const date=`${y}-${String(m).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const at=Date.parse(date+'T00:00:00Z')/60000;if(Math.min(end,at+1080)>Math.max(start,at-60))hits.push(date);}return hits;}
export function calculate(period,days,profile,inputs={}){const selected=days.filter(d=>d.date.startsWith(period+'-'));const expected=new Date(+period.slice(0,4),+period.slice(5),0).getDate();const missing=Math.max(0,expected-selected.length);return concepts.map(c=>{const rate=tariff(c,period,inputs),rows=[];let units=0,resolved=0,pending=0,candidates=0;const notes=[];let amount=null;const add=(d,r)=>{rows.push({date:d.date,status:d.status,start:d.start,end:d.end,...r});if(r.units===null)pending++;else {units+=r.units;if(!r.excluded)resolved++;}};
if(c.id==='night')for(const d of selected)add(d,nightResult(d,profile));
if(c.id==='nona')for(const d of selected){if(rest.has(d.status))continue;const t=interval(d.start,d.end);if(!t||!work.has(d.status)||['FORMACION','REVISION_MEDICA'].includes(d.status)||!d.ordinaryConfirmed||d.special==='NON_STOP_EXTRA'||d.category?.includes('CANVI_HORA')||d.category?.endsWith('_FINS_23H')){add(d,{units:null,reason:'Interval o condicions del servei no resolts'});continue;}const minutes=Math.min(60,Math.max(0,t.minutes-480));if(!minutes){add(d,{units:0,excluded:true,reason:'No supera 8 hores'});continue;}if(!d.nonaEligible||minutes%15){add(d,{units:null,candidateUnits:minutes/60,reason:minutes%15?'Tram conegut; arrodoniment del residu pendent':'Tram conegut; àmbit I-53 del dia pendent'});continue;}add(d,{units:minutes/60,reason:'Tram 8a–9a hora; quarts exactes i àmbit declarat'});}
if(c.id==='conveni')for(const d of selected){if(['AGCG','VISPERA_FESTIVO','COMPUTO_ACTUAL','COMPUTO_ANTERIOR','DCOM','RJ','VACACIONES','VAC_ANTERIOR','FORMACION','REVISION_MEDICA'].includes(d.status)){candidates++;add(d,{units:null,reason:profile?.percent===75?'Candidat: modalitat 75 %, proporció diària i puntualitat pendents':'Candidat: elegibilitat, puntualitat i proporció pendents'});}else if(uncertain.has(d.status))add(d,{units:null,reason:'Situació no resolta per al Plus Conveni'});} 
if(c.id==='festiu')for(const d of selected){if(new Date(d.date+'T12:00:00Z').getUTCDay()!==0||rest.has(d.status))continue;const t=interval(d.start,d.end),threshold=profile?.percent===100?240:profile?.percent?120:null;if(work.has(d.status)&&t&&threshold&&t.minutes>=threshold)candidates++;add(d,{units:null,reason:'Cal acreditar servei, descans propi, mínim i reducció per jornada; no és una unitat abonable confirmada'});}
if(c.id==='especial'){const events=new Set();for(const d of selected){if(rest.has(d.status))continue;const hits=specialEvents(d);if(hits.length){for(const x of hits)events.add(x);add(d,{units:null,reason:`Franja candidata ${hits.join(', ')}; servei ordinari, compatibilitats i parcialitat pendents`});}else if(!interval(d.start,d.end)||uncertain.has(d.status))add(d,{units:null,reason:'No es pot descartar solapament sense interval/situació resolts'});}candidates=events.size;notes.push('Esdeveniments únics; vigília i dia no es dupliquen. El període es refereix a la data d’inici de la jornada.');}
if(['aac','polivalencia'].includes(c.id)){if(profile?.percent){units=profile.percent/100;notes.push(`Component proporcional: ${profile.percent} % del mes.`);}else notes.push('Falta el percentatge contractual del període.');if(!inputs.monthConfirmed||!profile?.percent){pending=1;notes.push('Cal confirmar el perfil del període i mes íntegre elegible sense ajustos.');}else{resolved=1;if(rate)amount=rate.value*units;}}
if(c.id==='vacances')for(const d of selected){if(d.status==='VACACIONES'||(d.status==='VAC_ANTERIOR'&&d.priorOrigin==='VACACIONES')){add(d,{units:1,reason:'Dia de vacances declarat; liquidació a confirmar'});}else if(d.status==='VAC_ANTERIOR'&&!d.priorOrigin||uncertain.has(d.status))add(d,{units:null,reason:'Vacances/origen no confirmats'});} 
if(['night','nona'].includes(c.id)&&resolved&&rate)amount=units*rate.value;
if(c.id==='vacances'&&resolved&&rate&&inputs.vacationConfirmed)amount=units*rate.value;
if(c.id==='vacances'&&!inputs.vacationConfirmed)notes.push('Cal confirmar dies liquidables; mitjana individual dels 12 mesos, no tarifa universal.');
if(!rate)notes.push(c.rateNote||'No consta tarifa acreditada per al període seleccionat.');
if(rate)notes.push(`Tarifa: ${rate.value} €/${c.unit} · ${rate.source}.`);
if(!['aac','polivalencia'].includes(c.id)&&missing)notes.push(`${missing} dates del mes sense dades; no es consideren zero.`);
const known=resolved>0||rows.some(r=>r.units!==null&&Number.isFinite(r.units));
return {id:c.id,units:known?units:null,resolved,pending,missing:['aac','polivalencia'].includes(c.id)?0:missing,candidates,amount,rate,rows,notes,state:amount!==null?'Estimació · subtotal conegut':known?'Unitats conegudes · import pendent':selected.length?'Pendent de dades o condicions':'Normativa disponible'};});}
